version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT:-8000}:8000"
    environment:
      - PORT=${PORT:-8000}
      - DATABASE_URL=${DATABASE_URL:-postgresql://sprintsync:sprintsync@db:5432/sprintsync}
      - SECRET_KEY=${SECRET_KEY:-09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7}
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
      - DEBUG=${DEBUG:-false}
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-sprintsync}
      - POSTGRES_USER=${POSTGRES_USER:-sprintsync}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-sprintsync}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    # Remove port exposure for security

volumes:
  postgres_data: 